---
- name: '[HEAT-ANSIBLE][HEAT-CREATE] Heat Creation'
  hosts: all
  remote_user: root
  vars_files:
    - "vault/vault.yml"
  roles:
    - { role: heat-ansible }
      
- name: '[HEAT-ANSIBLE] '
  hosts: inv
  delegate_to: localhost
  remote_user: cloud-user
  vars_files: 
    - "vault/vault.yml"
  tasks:
    - include: roles/heat-ansible/tasks/config_stack.yml

