---

# The VM must to be accessible and reachable from the Ansible Tower 
# This connection will be origined by the Ansible Tower to the FIP assigned
# for the VM
- name: "[VM_TEST] Wait to the instance to get the ssh service up"
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    search_regex: OpenSSH
    delay: 20
    timeout: 300
  connection: local
  become: false

- name: "[VM_TEST] Create a file called '/tmp/testfile.txt' with the content 'hello world'."
  copy: 
    content: "hello world\n" 
    dest: "/tmp/testfile.txt"

- name: "[VM_TEST] Echo Some Stuff"
  shell: "/usr/bin/hostname"

- name: "[VM_TEST] Install httpd for example"
  yum: 
    name: "{{ item }}"
    state: latest
  with_items:
   - httpd
   - php
   - php-mysql
   - git
   - libsemanage-python
   - libselinux-python

- name: "[VM_TEST] Creates the index.php file"
  template: 
    src: "roles/heat-ansible/templates/index.php.j2"
    dest: "/var/www/html/index.php"

- name: "[VM_TEST] http service state"
  service: 
    name: httpd 
    state: started 
    enabled: yes
