---

- name: "[VM_TEST] Wait to the instance to get the ssh service up"
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    search_regex: OpenSSH
    delay: 20
    timeout: 300
  connection: local
  become: false

- name: "Create a file called '/tmp/testfile.txt' with the content 'hello world'."
  delegate_to: localhost
  copy: 
    content: "hello world\n" 
    dest: "/tmp/testfile.txt"

- name: "[VM_TEST] Echo Some Stuff"
  shell: "echo $(hostname -i)"
