---
# tasks file for heat-ansible

- name: 'Get Tenant facts'
  delegate_to: localhost
  os_project:
    name: "{{ project }}"
    state: present
    enabled: True
    validate_certs: false
  environment:
    OS_USERNAME: "{{ ADMIN_USER }}"
    OS_PASSWORD: "{{ OSP_PASS }}"
    OS_AUTH_URL: "http://{{ KEYSTONE_ENDPOINT }}:{{ KEYSTONE_ADMIN_PORT }}/v3/"
    OS_IDENTITY_API_VERSION: "3"
    OS_PROJECT_NAME: "admin"
    OS_PROJECT_DOMAIN_NAME: "Default"
    OS_USER_DOMAIN_NAME: "Default"
    OS_REGION_NAME: "RegionOne"
  register: os_tenant

- name: 'Get Network facts'
  delegate_to: localhost
  environment:
    OS_USERNAME: "{{ ADMIN_USER }}"
    OS_PASSWORD: "{{ OSP_PASS }}"
    OS_AUTH_URL: "http://{{ KEYSTONE_ENDPOINT }}:{{ KEYSTONE_ADMIN_PORT }}/v3/"
    OS_IDENTITY_API_VERSION: "3"
    OS_PROJECT_NAME: "admin"
    OS_PROJECT_DOMAIN_NAME: "Default"
    OS_USER_DOMAIN_NAME: "Default"
    OS_REGION_NAME: "RegionOne"
  os_networks_facts:
    validate_certs: false
    filters:
      tenant_id: "{{ os_tenant.project.id }}"

- name: 'Getting the correct network details'
  set_fact:
    os_net: "{{ item }}"
  when: '"({{ zone_name }})" in item.name'
  with_list: "{{ openstack_networks }}"  
 
- name: 'Create the Heat Orchestration Template rendered'
  delegate_to: localhost
  template:
  	src: "{{ heat_template }}"
    dest: "{{ code_dest_dir }}/{{ heat-template }}"
    mode: 0644

- name: 'Create Stack' 
  delegate_to: localhost
  environment:
    OS_USERNAME: "{{ ADMIN_USER }}"
    OS_PASSWORD: "{{ OSP_PASS }}"
    OS_AUTH_URL: "http://{{ KEYSTONE_ENDPOINT }}:{{ KEYSTONE_ADMIN_PORT }}/v3/"
    OS_IDENTITY_API_VERSION: "3"
    OS_PROJECT_NAME: "admin"
    OS_PROJECT_DOMAIN_NAME: "Default"
    OS_USER_DOMAIN_NAME: "Default"
    OS_REGION_NAME: "RegionOne"
  os_stack: 
	name: "{{ stack_name }}"
    tag: "{{ stack_tag }}"
	state: present
	template: "{{ code_dest_dir }}/{{ heat_template }}"
  register: stack_create
