---
# tasks file for heat-ansible

- name: '[HEAT-ANSIBLE] Get tenant for heat-deployment'
  delegate_to: localhost
  os_project:
    name: "{{ project }}"
    state: present
    enabled: True
    validate_certs: false
  environment:
    OS_USERNAME: "admin"
    OS_PASSWORD: "{{ OSP_PASS }}"
    OS_AUTH_URL: "http://{{ KEYSTONE_ENDPOINT }}:{{ KEYSTONE_ADMIN_PORT }}/v3/"
    OS_IDENTITY_API_VERSION: "3"
    OS_PROJECT_NAME: "admin"
    OS_PROJECT_DOMAIN_NAME: "Default"
    OS_USER_DOMAIN_NAME: "Default"
    OS_REGION_NAME: "RegionOne"
  register: os_tenant

  #- name: 'Debug'
  #  debug: 
  #    msg: "{{ os_tenant }}"

- name: '[HEAT-ANSIBLE] Get Network facts'
  delegate_to: localhost
  environment:
    OS_USERNAME: "{{ ADMIN_USER }}"
    OS_PASSWORD: "{{ OSP_PASS }}"
    OS_AUTH_URL: "http://{{ KEYSTONE_ENDPOINT }}:{{ KEYSTONE_ADMIN_PORT }}/v3/"
    OS_IDENTITY_API_VERSION: "3"
    OS_PROJECT_NAME: "admin"
    OS_PROJECT_DOMAIN_NAME: "Default"
    OS_USER_DOMAIN_NAME: "Default"
    OS_REGION_NAME: "RegionOne"
  os_networks_facts:  
    validate_certs: false
    filters:
      tenant_id: "{{ os_tenant.project.id }}"
 
- name: 'Debug'
  debug:
    msg: "{{ openstack_networks }}"

- name: '[HEAT-ANSIBLE] Getting the correct network details'
  set_fact:
    os_net: "{{ item }}"
  when: '"({{ net_name }})" in item.name'
  with_list: "{{ openstack_networks }}"  

- name: '[HEAT-ANSIBLE] Adding the ssh_key pair'
  delegate_to: localhost
  environment:
    OS_USERNAME: "{{ ADMIN_USER }}"
    OS_PASSWORD: "{{ OSP_PASS }}"
    OS_AUTH_URL: "http://{{ KEYSTONE_ENDPOINT }}:{{ KEYSTONE_ADMIN_PORT }}/v3/"
    OS_IDENTITY_API_VERSION: "3"
    OS_PROJECT_NAME: "admin"
    OS_PROJECT_DOMAIN_NAME: "Default"
    OS_USER_DOMAIN_NAME: "Default"
    OS_REGION_NAME: "RegionOne"
  os_keypair: 
    name: "{{ ssh_key_name }}"
    public_key: "{{ ssh_key }}"
    state: present
    wait: yes 

- name: '[HEAT-ANSIBLE] Create the directory for ansible-cf code'
  delegate_to: localhost
  file: 
    path: "{{ code_dest_dir }}"    
    state: directory
    mode: 0755
 
- name: '[HEAT-ANSIBLE] Create the Heat Orchestration Template rendered'
  delegate_to: localhost
  template:
    src: "{{ heat_template }}"
    dest: "{{ code_dest_dir }}/{{ heat_template }}"
    mode: 0644

- name: '[HEAT-ANSIBLE] Create Stack' 
  delegate_to: localhost
  environment:
    OS_USERNAME: "{{ ADMIN_USER }}"
    OS_PASSWORD: "{{ OSP_PASS }}"
    OS_AUTH_URL: "http://{{ KEYSTONE_ENDPOINT }}:{{ KEYSTONE_ADMIN_PORT }}/v3/"
    OS_IDENTITY_API_VERSION: "3"
    OS_PROJECT_NAME: "admin"
    OS_PROJECT_DOMAIN_NAME: "Default"
    OS_USER_DOMAIN_NAME: "Default"
    OS_REGION_NAME: "RegionOne"
  os_stack: 
    name: "{{ stack_name }}"
    state: present
    template: "{{ code_dest_dir }}/{{ heat_template }}"
  register: stack_create
