---

- name: '[HEAT-ANSIBLE] Get tenant for heat-deployment'
  delegate_to: localhost
  os_project:
    name: "{{ project }}"
    state: present
    enabled: True
    validate_certs: false
  environment: "{{ auth_v3 }}"
  register: os_tenant

  #- name: 'Debug'
  #  debug: 
  #    msg: "{{ os_tenant }}"

- name: '[HEAT-ANSIBLE] Get Network facts'
  delegate_to: localhost
  environment: "{{ auth_v3 }}"
  os_networks_facts:  
    validate_certs: false
    filters:
      tenant_id: "{{ os_tenant.project.id }}"
 
- name: 'Debug'
  debug:
    msg: "{{ openstack_networks }}"

- name: '[HEAT-ANSIBLE] Getting the correct network details'
  set_fact:
    os_net: "{{ item }}"
  when: '"({{ net_name }})" in item.name'
  with_list: "{{ openstack_networks }}"  

- name: '[HEAT-ANSIBLE] Adding the ssh_key pair'
  delegate_to: localhost
  environment: "{{ auth_v3 }}"
  os_keypair: 
    name: "{{ ssh_key_name }}"
    public_key: "{{ ssh_key }}"
    state: present
    wait: yes 
